-- liquibase formatted sql

-- changeset evgeniyth:1
create table "customers"
(
    customer_id      integer generated by default as identity primary key,
    passport_series  integer check (passport_series > 999 AND passport_series <= 9999),
    passport_number  integer check (passport_number > 99999 AND passport_number <= 999999),
    last_name        varchar(50) not null,
    first_name       varchar(50) not null,
    patronymic       varchar(50) not null,
    birthday         varchar(10) not null,
    address_id       integer     not null references addresses (address_id),
    contact_id       integer references contacts (contact_id),
    status           varchar(10) not null,
    create_date_time timestamp,
    update_date_time timestamp
);

create table "addresses"
(
    address_id integer generated by default as identity primary key,
    country    varchar(20) not null,
    city       varchar(20) not null,
    street     varchar(30) not null,
    house      varchar(10) not null,
    apartment  integer check (apartment > 0)
);

create table "contacts"
(
    contact_id   integer generated by default as identity primary key,
    phone_number varchar(15) not null unique,
    email        varchar(30) not null unique
);

create table "transactions"
(
    transaction_id           integer generated by default as identity primary key,
    customer_id              integer check ( customer_id > 0 ) not null references customers (customer_id),
    senders_account_number   varchar(20)                       not null,
    recipient_account_number varchar(20)                       not null,
    amount                   decimal check (amount >= 0),
    currency                 varchar(5)                        not null,
    transaction_type         varchar(15)                       not null,
    date_time_transaction    timestamp
);

create table "cards"
(
    card_id           integer generated by default as identity primary key,
    customer_id       integer check ( customer_id > 0 ) not null references customers (customer_id),
    card_number       varchar(16)                       not null,
    cvv               varchar(3)                        not null,
    account_number    varchar(20)                       not null,
    balance           decimal check ( balance >= 0 ),
    currency          varchar(5)                        not null,
    status            varchar(10)                       not null,
    opening_date_time timestamp,
    update_date_time  timestamp
);

create table "savings_accounts"
(
    account_id        integer generated by default as identity primary key,
    customer_id       integer check ( customer_id > 0 ) not null,
    account_number    varchar(20)                       not null,
    balance           decimal check ( balance >= 0 ),
    currency          varchar(5)                        not null,
    status            varchar(10)                       not null,
    opening_date_time timestamp,
    update_date_time  timestamp
);